services:
  app: 
    build: .
    container_name: python-server
    command: fastapi run src/main.py --port 80 --reload
    ports:
      - 80:80
      - 5678:5678
    volumes:
      - .:/code
  
  redis:
    image: redis:alpine
    